In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/full_survey_data.csv')

/var/folders/b3/glj_22g92pl25nkdvjvxnzz00000gn/T/ipykernel_37316/2232081259.py:1: DtypeWarning: Columns (10,11,12,15,16,17,18,19,20,21,22,24,27,37,40,41,42,43,44,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,69,74,75,76,78,88,91,94,95,104,113,114,115,116,118,121,122,123,124,125,132,135,137,138,141,142,151,160,161,162,163,165,168,169,170,171,172,179,182,184,185,188,189,198,207,208,209,210,212,215,216,217,218,219,226,229,231,232,236,245,254,255,256,257,259,262,263,264,265,266,273,276,278,279,283,292,301,302,303,304,306,309,310,312,313,320,325,326,330,339,348,349,350,351,353,356,357,359,360,367,372,373,377,386,395,396,397,398,400,403,404,406,407,414,419,420,424,433,443,444,445,446,447,448,450,451,452,453,454,455,456,458,459,460,461,462,463,464,465,466,467,469,470,471,472,473,474,475,476,478,479,480,481,482,500,501,502,508,510,515,516,522,524,525,526,533,538,547,556,561,565,566,567,574,580,581,582,591,600,603,607,608,609,616,620,624,633,680,681,682,687,688,694,696,697,698,705,710,719,728,733,738,739,746,752,754,763,772,775,779,780,781,788,792,796,805,814,829,849,850,852,854,859,860,866,868,869,870,877,882,891,900,905,910,911,918,924,926,935,944,947,952,953,960,964,968,977,987,989,991,998,1003,1012,1021,1022,1024,1026,1031,1032,1040,1041,1042,1063,1072,1073,1074,1076,1077,1079,1080,1082,1085,1087,1089,1090,1092,1094,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1119,1124,1125,1132,1136,1140,1149,1159,1161,1184,1193,1194,1196,1197,1198,1203,1204,1224,1288,1291,1296,1297,1304,1308,1312,1321,1331,1333,1347,1365,1366,1367,1369,1370,1371,1373,1377,1379,1380,1383,1384,1385,1387,1389,1390,1393,1396,1398,1399,1400,1401,1404,1405,1406,1407,1408,1409,1410,1412,1413,1414,1415,1416,1417,1422,1423,1424,1425,1426,1431,1432,1433,1434,1435,1440,1444,1445,1446,1447,1448,1449,1452,1453,1458,1461,1462,1467,1468,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,1511,1512,1513,1514,1515,1516,1517,1518,1519,1520,1521,1522,1523,1524,1525,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1592,1593,1594,1595,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/full_survey_data.csv')

In [3]:
df.country.unique()

array(['burkina_faso', 'burundi', 'bolivia', 'drc', "cote d'ivoire",
       'costa_rica', 'ecuador', 'ethiopia', 'ghana', 'gambia',
       'guatemala', 'honduras', 'india', 'kenya', 'cambodia', 'comoros',
       'morocco', 'mali', 'Mali', 'malawi', 'niger', 'nigeria',
       'nicaragua', 'nepal', 'peru', 'philipines', 'palestine', 'rwanda',
       'sierra leone', 'senegal', 'el_salvador', 'tanzania', 'uganda',
       'vietnam', 'south africa', 'zambia'], dtype=object)

In [23]:
disasters = pd.read_excel('../data/public_emdat_custom_request_2025-09-18_0365efe8-4cf6-409a-885a-7a5e8e044c1c.xlsx')

In [12]:
disasters

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,Entry Date,Last Update
0,2012-0509-NPL,No,nat-met-ext-col,Natural,Meteorological,Extreme temperature,Cold wave,GLIDE:CW-2013-000001,NaN,NPL,...,NaN,NaN,NaN,NaN,NaN,NaN,74.263729,"[{""adm1_code"":2152,""adm1_name"":""Central""},{""ad...",2013-04-15,2023-09-25
1,2013-0001-SEN,No,tec-tra-roa-roa,Technological,Transport,Road,Road,NaN,NaN,SEN,...,NaN,NaN,NaN,NaN,NaN,NaN,74.263729,NaN,2013-01-02,2023-09-25
2,2013-0002-ZAF,No,tec-mis-fir-fir,Technological,Miscellaneous accident,Fire (Miscellaneous),Fire (Miscellaneous),NaN,Shanty town,ZAF,...,NaN,NaN,NaN,NaN,NaN,NaN,74.263729,NaN,2014-03-21,2023-09-25
3,2013-0004-TZA,No,tec-tra-wat-wat,Technological,Transport,Water,Water,NaN,NaN,TZA,...,NaN,NaN,NaN,NaN,NaN,NaN,74.263729,NaN,2013-02-13,2023-09-25
4,2013-0005-MLI,No,tec-tra-wat-wat,Technological,Transport,Water,Water,NaN,NaN,MLI,...,NaN,NaN,NaN,NaN,NaN,NaN,74.263729,NaN,2013-02-13,2023-09-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2075,2024-0971-IND,No,tec-mis-mis-mis,Technological,Miscellaneous accident,Miscellaneous accident (General),Miscellaneous accident (General),NaN,Alcool frelaté,IND,...,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,2025-05-16,2025-05-16
2076,2024-9075-COL,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,GLIDE:DR-2024-000013,NaN,COL,...,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,"[{""adm1_code"":939,""adm1_name"":""Boyaca""},{""adm1...",2024-02-13,2024-06-14
2077,2024-9131-ZMB,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,GLIDE:DR-2024-000018,NaN,ZMB,...,NaN,NaN,NaN,NaN,2261.0,2261.0,100.000000,NaN,2024-03-12,2025-02-07
2078,2024-9197-MWI,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,GLIDE:DR-2024-000066|GLIDE:DR-2024-000069,NaN,MWI,...,NaN,NaN,NaN,NaN,400000.0,400000.0,100.000000,NaN,2024-04-05,2025-02-21
2079,2024-9277-VNM,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,VNM,...,NaN,NaN,NaN,NaN,10000.0,10000.0,100.000000,NaN,2024-05-03,2024-08-12

In [25]:
rhomis_meta = pd.read_excel('../documentation/project_metadata.xlsx', header=1)
rhomis_meta

,RHoMIS ID,ID Proj,ID Country,Year,Lead Institute,Other Partners,Project Full Name,Project description,Project contact person,Project Contact email address,...,Representative Of,Total Number of Households Interviewed,Survey Purpose,Total Number of Surveys Planned,Iteration,Related surveys,Modules Used,RHoMIS version used,Changes to Core,Consent Type
0,MW_CFG_2015,CFG,MW,2015,CIMMYT,NASFAM,CCAFS,This RHoMIS application took place within the ...,Amon J. Chinyophiro,achinyophiro@gmail.com,...,Regions of Lilongwe North and South,160,Evaluation of the welfare benefits of gender s...,1.0,1.0,NaN,"Core, HFIAS, Gender Attitudes",1.2,"This was an older RHoMIS application, before t...",Oral
1,BF_CW2_2015,CW2,BF,2015,ILRI,IWMI,CCAFS-WLE,This RHoMIS application took place within the ...,Augustine Ayantunde,a.ayantunde@cgiar.org,...,Communes,200,Baseline,1.0,1.0,ML_CW1_2015,"Core, water harvesting",1.2,This was a paper version application based on ...,Oral
2,ML_CW1_2015,CW1,ML,2015,ILRI,IWMI,CCAFS-WLE,This RHoMIS application took place within the ...,Augustine Ayantunde,a.ayantunde@cgiar.org,...,"Communes of Cinzana, Dioro, Djouna and Katiena",200,Baseline,1.0,1.0,BF_CW2_2015,Core,1.2,This was a paper version application based on ...,Oral
3,GT_S4N_2015,S4N,GT,2015,Bioversity International,CATIE,Prueba3,Prueba3; a USAID funded project in the Trifini...,Jacob van Etten,j.vanetten@cgiar.org,...,Larger Trifinio area,164,Baseline,2.0,1.0,"GT_S4N_2015, HN_S4N_2015, SV_S4N_2015, GT_S4N_...",Core,1.2,"This was a very early RHoMIS application, so t...",Oral
4,HN_S4N_2015,S4N,HN,2015,Bioversity International,CATIE,Prueba3,Prueba3; a USAID funded project in the Trifini...,Jacob van Etten,j.vanetten@cgiar.org,...,Larger Trifinio area,28,Baseline,2.0,1.0,"GT_S4N_2015, HN_S4N_2015, SV_S4N_2015, GT_S4N_...",Core,1.2,"This was a very early RHoMIS application, so t...",Oral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,VN_VSC_2022,VSC,VN,2022,ABC,NaN,V-Scope,Enhancing smallholder livelihoods in the Centr...,An Notenbaert,a.notenbaert@cgiar.org,...,Farming households in three districts of Dak L...,940,NaN,NaN,NaN,NaN,"Core, Livestock Feed",1.6,NaN,"Oral, optional signature"
116,ET_ECO_2023,ECO,ET,2023,TreeAid,NaN,TreeAid,The project will enhance the management of exi...,David Baines,david.baines@treeaid.org,...,smallholder farming households,215,NaN,NaN,NaN,NaN,"Core,Forest Products,FIES,Voice Choice Control",1.6,NaN,"Oral, optional signature"
117,ET_LCS_2022,LCS,ET,2022,ILRI,NaN,LCSR,The Livestock and Climate initiative conducted...,Birgit Habermann,B.Habermann@cgiar.org,...,smallholder livestock keepers (sheep fattening),1016,"Selection of pioneers, baseline",1.0,1.0,KE_LCS_2022,Core,1.6,Gender removed,"Oral, optional signature"
118,KE_LCS_2022,LCS,KE,2022,ILRI,NaN,LCSR,The Livestock and Climate initiative conducted...,Birgit Habermann,B.Habermann@cgiar.org,...,smallholder livestock keepers (dairy farming),1016,"Selection of pioneers, baseline",1.0,1.0,ET_LCS_2022,Core,1.6,Gender removed,"Oral, optional signature"
119,PH_USM_2022,USM,PH,2022,WUR,NaN,SustainAg Philippines,Enabling the transition to sustainable smallho...,Don van Luijn,don.vanluijn@wur.nl,...,Smallholder farming households in selected adm...,2552,"Characterisation, baseline",1.0,1.0,NaN,"Core,Crop_petsts; Innovation, Mem.groups; NRM_...",1.6,No major changes,"Oral, optional signature"

In [26]:
rhomis_meta = rhomis_meta[['RHoMIS ID','Country full name','Regions','Year']]
rhomis_meta

,RHoMIS ID,Country full name,Regions,Year
0,MW_CFG_2015,Malawi,Lilongwe,2015
1,BF_CW2_2015,Burkina Faso,Yatenga,2015
2,ML_CW1_2015,Mali,Segou,2015
3,GT_S4N_2015,Guatemala,Trifinio,2015
4,HN_S4N_2015,Honduras,Trifinio,2015
...,...,...,...,...
115,VN_VSC_2022,Vietnam,Dak Lak,2022
116,ET_ECO_2023,Ethiopia,Metema,2023
117,ET_LCS_2022,Ethiopia,Amhara,2022
118,KE_LCS_2022,Kenya,"Nandi, Bomet",2022
119,PH_USM_2022,Phillipines,North Cotabato - eastern part of Region XII,2022

In [24]:
disasters = disasters[['DisNo.','Country','Location','Start Year']]
disasters

,DisNo.,Country,Location,Start Year
0,2012-0509-NPL,Nepal,"Central, Eastern, Far Western, Mid Western, We...",2013
1,2013-0001-SEN,Senegal,Touba,2013
2,2013-0002-ZAF,South Africa,Cape town,2013
3,2013-0004-TZA,United Republic of Tanzania,Tanganyika make,2013
4,2013-0005-MLI,Mali,Between Niafunké and Banicane (North),2013
...,...,...,...,...
2075,2024-0971-IND,India,Tamil Nadu,2024
2076,2024-9075-COL,Colombia,"Boyaca, Cordoba, Cundinamarca, Huila, Santande...",2024
2077,2024-9131-ZMB,Zambia,"Shangombo, Sinazongwe, Chirundu, Siavonga, Chi...",2024
2078,2024-9197-MWI,Malawi,NaN,2024
2079,2024-9277-VNM,Viet Nam,"Can Duoc, Can Giuoc areas (Long An province); ...",2024

In [20]:
pip install unidecode

Defaulting to user installation because normal site-packages is not writeable
Collecting unidecode
  Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
     |████████████████████████████████| 235 kB 4.1 MB/s eta 0:00:01
Installing collected packages: unidecode
Successfully installed unidecode-1.4.0
WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [9]:
disasters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2080 entries, 0 to 2079
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DisNo.    2080 non-null   object
 1   Country   2080 non-null   object
 2   Location  1979 non-null   object
dtypes: object(3)
memory usage: 48.9+ KB

In [7]:
import unidecode
disasters['Location'].fillna('').astype(str).str.lower().str.strip().apply(unidecode.unidecode)

0       central, eastern, far western, mid western, we...
1                                                   touba
2                                               cape town
3                                         tanganyika make
4                   between niafunke and banicane (north)
                              ...
2075                                           tamil nadu
2076    boyaca, cordoba, cundinamarca, huila, santande...
2077    shangombo, sinazongwe, chirundu, siavonga, chi...
2078
2079    can duoc, can giuoc areas (long an province); ...
Name: Location, Length: 2080, dtype: object

In [8]:
disasters['Location'] = disasters['Location'].fillna('').astype(str).str.lower().str.strip().apply(unidecode.unidecode)   
rhomis_meta['Regions'] = rhomis_meta['Regions'].fillna('').astype(str).str.lower().str.strip().apply(unidecode.unidecode)

/var/folders/b3/glj_22g92pl25nkdvjvxnzz00000gn/T/ipykernel_37316/68648911.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rhomis_meta['Regions'] = rhomis_meta['Regions'].fillna('').astype(str).str.lower().str.strip().apply(unidecode.unidecode)

In [12]:
rhomis_meta

,RHoMIS ID,Country full name,Regions
0,MW_CFG_2015,Malawi,lilongwe
1,BF_CW2_2015,Burkina Faso,yatenga
2,ML_CW1_2015,Mali,segou
3,GT_S4N_2015,Guatemala,trifinio
4,HN_S4N_2015,Honduras,trifinio
...,...,...,...
115,VN_VSC_2022,Vietnam,dak lak
116,ET_ECO_2023,Ethiopia,metema
117,ET_LCS_2022,Ethiopia,amhara
118,KE_LCS_2022,Kenya,"nandi, bomet"
119,PH_USM_2022,Phillipines,north cotabato - eastern part of region xii

In [9]:
from rapidfuzz import process, fuzz
#clean locations


matches = []
for loc in rhomis_meta['Regions']:
    best = process.extractOne(loc, disasters['Location'], scorer=fuzz.token_sort_ratio)
    if best[1] > 70:  # similarity threshold
        matches.append((loc, best[0], best[1]))

In [10]:
matches

[('ukambani', 'mumbai', 71.42857142857143),
 ('ratanakiri province', 'tanganyika province', 73.6842105263158),
 ('bukavu', 'bukavu', 100.0),
 ('west', 'west', 100.0),
 ('segou region', 'somali region', 72.0),
 ('eastern province', 'eastern cape province', 86.48648648648648),
 ('zinder, niger', 'near zinder', 83.33333333333334),
 ('amhara', 'amaga', 72.72727272727273),
 ('kenema', 'kenge', 72.72727272727273),
 ('east', 'west', 75.0),
 ('ayacucho, huancavelica, junin',
  'cusco, huancavelica provinces',
  72.41379310344827),
 ('sucre', 'surate', 72.72727272727273),
 ('kaduna and kano states', 'kaduna state', 70.58823529411764),
 ('south bf', 'south', 76.92307692307692),
 ('north-west, east', 'north-west', 76.92307692307692),
 ('western', 'west', 72.72727272727273),
 ('north-west, east', 'north-west', 76.92307692307692),
 ('amhara', 'amaga', 72.72727272727273),
 ('', '', 100.0),
 ('segou, mopti,', 'mopti region', 72.0),
 ('tahoua, dosso, tillaberi',
  'maradi, tahoua, tillaberi, dosso',
  85.71428571428572),
 ('', '', 100.0),
 ('north-east', 'north-west', 90.0),
 ('', '', 100.0),
 ('', '', 100.0),
 ('dak lak', 'dak lak', 100.0),
 ('amhara', 'amaga', 72.72727272727273)]

Empty DataFrame
Columns: [id_unique, id_hh, id_rhomis_dataset, id_form, id_proj, year, gps_lat_rounded, gps_lon_rounded, gps_alt, gps_source, start_time_user, starttime_auto, starttime_calculated, iso_country_code, country, region, sublocation, local_currency, participation, beneficiary, respondent_is_head, respondentsex, household_position, household_type, work_away, age_malehead, age_femalehead, education_level, count_people, children_under_4, children_4to10, males11to24, females11to24, males25to50, females25to50, malesover50, femalesover50, land_tenure, landcultivated, unitland, areaunits_other, landowned, unitland_owned, land_ownership, areaunits_other_own, landrentin, unitland_rentin, landrentout, unitland_rentout, areaunits_other_rent, farm_labour, land_slope, homegarden, grow_crops, crops_all, crops_other1, crops_other2, crops_other3, farm_planning_who, vegetables_which, fruits_which, harvest_early, early_harvest_crops, early_harvest_reasons, early_harvest_reasons_other, crops, crop_count, crop_name_1, crop_label_1, crop_harvest_1, crop_yield_1, crop_yield_units_1, crop_yield_units_numeric_1, crop_harvest_kg_per_year_1, crop_intercrop_1, crop_land_area_1, crop_yield_units_other_1, crop_use_1, crop_consumed_prop_1, crop_consumed_prop_numeric_1, crop_consumed_kg_per_year_1, crop_calories_kcal_per_kg_1, crop_calories_consumed_kcal_1, mean_crop_price_lcu_per_kg_1, value_crop_consumed_lcu_1, crop_sold_prop_1, crop_sold_prop_numeric_1, crop_sold_kg_per_year_1, crop_feed_lstk_prop_1, crop_sold_income_1, crop_sold_price_quantityunits_1, crop_sold_units_numeric_1, crop_income_per_year_1, crop_price_1, crop_price_quantityunits_other_1, crop_who_control_revenue_1, male_adult_crop_income_per_year_1, male_youth_crop_income_per_year_1, female_adult_crop_income_per_year_1, female_youth_crop_income_per_year_1, ...]
Index: []

[0 rows x 1599 columns]

In [26]:
rhomis_meta['Country full name'].unique()

array(['Malawi', 'Burkina Faso', 'Mali', 'Guatemala', 'Honduras',
       'El Salvador', 'Tanzania', 'Ethiopia', 'Kenya', 'India',
       'Cambodia', 'Laos', 'Vietnam', 'DRC', 'Ghana', 'Uganda', 'Zambia',
       'Costa Rica', 'Niger', 'Ivory Coast', 'Ecuador', 'Nicaragua',
       'Rwanda', 'Sierra Leone', 'Palestine', 'Senegal', 'Burundi',
       'Peru', 'Bolivia', 'Nigeria', 'India ', 'Morocco', 'The Comoros',
       'South Africa', 'Gambia', 'Nepal', 'Phillipines'], dtype=object)

In [27]:
disasters.Country.unique()

array(['Nepal', 'Senegal', 'South Africa', 'United Republic of Tanzania',
       'Mali', 'Ghana', 'Malawi', 'Ecuador', 'Philippines',
       'Sierra Leone', 'State of Palestine', 'Kenya', 'Peru',
       'Bolivia (Plurinational State of)', 'Colombia', 'Zambia', 'India',
       'Viet Nam', 'Comoros', 'Nigeria', 'Ethiopia', 'Uganda',
       'Democratic Republic of the Congo', 'Morocco', 'Guatemala',
       'Burkina Faso', 'Niger', 'Nicaragua', 'Cambodia', 'Gambia',
       'Costa Rica', 'Honduras', 'El Salvador', 'Côte d’Ivoire',
       'Burundi', 'Rwanda'], dtype=object)

In [27]:
#Palestine, DRC, Comoros, Ivory Coast, Phillipines, Tanzania, Bolivia, Vietnam, 

disasters['Country'] = disasters['Country'].replace({
    'Côte d’Ivoire': 'Ivory Coast',
    'Democratic Republic of the Congo': 'DRC',
    'Viet Nam': 'Vietnam',
    'United Republic of Tanzania': 'Tanzania',
    'Philippines': 'Phillipines',
    'Bolivia (Plurinational State of)': 'Bolivia',
    'State of Palestine': 'Palestine',
    'Comoros': 'The Comoros'
})
disasters.Country.unique()

array(['Nepal', 'Senegal', 'South Africa', 'Tanzania', 'Mali', 'Ghana',
       'Malawi', 'Ecuador', 'Phillipines', 'Sierra Leone', 'Palestine',
       'Kenya', 'Peru', 'Bolivia', 'Colombia', 'Zambia', 'India',
       'Vietnam', 'The Comoros', 'Nigeria', 'Ethiopia', 'Uganda', 'DRC',
       'Morocco', 'Guatemala', 'Burkina Faso', 'Niger', 'Nicaragua',
       'Cambodia', 'Gambia', 'Costa Rica', 'Honduras', 'El Salvador',
       'Ivory Coast', 'Burundi', 'Rwanda'], dtype=object)

In [36]:
rhomis_meta

,RHoMIS ID,Country full name,Regions
0,MW_CFG_2015,Malawi,lilongwe
1,BF_CW2_2015,Burkina Faso,yatenga
2,ML_CW1_2015,Mali,segou
3,GT_S4N_2015,Guatemala,trifinio
4,HN_S4N_2015,Honduras,trifinio
...,...,...,...
115,VN_VSC_2022,Vietnam,dak lak
116,ET_ECO_2023,Ethiopia,metema
117,ET_LCS_2022,Ethiopia,amhara
118,KE_LCS_2022,Kenya,"nandi, bomet"
119,PH_USM_2022,Phillipines,north cotabato - eastern part of region xii

In [28]:
disasters['Location'] = disasters['Location'].fillna('').astype(str).str.lower().str.strip().apply(unidecode.unidecode)   
rhomis_meta['Regions'] = rhomis_meta['Regions'].fillna('').astype(str).str.lower().str.strip().apply(unidecode.unidecode)

/var/folders/b3/glj_22g92pl25nkdvjvxnzz00000gn/T/ipykernel_37316/1856088524.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rhomis_meta['Regions'] = rhomis_meta['Regions'].fillna('').astype(str).str.lower().str.strip().apply(unidecode.unidecode)

0       central, eastern, far western, mid western, we...
1                                                   touba
2                                               cape town
3                                         tanganyika make
4                   between niafunke and banicane (north)
                              ...
2075                                           tamil nadu
2076    boyaca, cordoba, cundinamarca, huila, santande...
2077    shangombo, sinazongwe, chirundu, siavonga, chi...
2078
2079    can duoc, can giuoc areas (long an province); ...
Name: Location, Length: 2080, dtype: object

In [29]:


matches = []

for country in rhomis_meta['Country full name'].unique():
    rhomis = rhomis_meta[rhomis_meta['Country full name'] == country]
    disaster_countries = disasters[disasters['Country'] == country]

    if disaster_countries.empty:   # skip if no locations for that country
        continue

    for loc in rhomis['Regions']:
        best = process.extractOne(loc, disaster_countries['Location'], scorer=fuzz.token_sort_ratio)
        if best is not None and best[1] > 65:  # similarity threshold
            matches.append((country, loc, best[0], best[1]))

In [30]:
matches

[('Mali', 'segou, mopti,', 'mopti region', 72.0),
 ('Mali', '', '', 100.0),
 ('Guatemala', '', '', 100.0),
 ('Tanzania', '', '', 100.0),
 ('Ethiopia', 'amhara', 'amhara state', 66.66666666666667),
 ('Ethiopia', 'amhara', 'amhara state', 66.66666666666667),
 ('Ethiopia', 'amhara', 'amhara state', 66.66666666666667),
 ('Vietnam', 'dak lak', 'dak lak', 100.0),
 ('DRC', 'bukavu', 'bukavu', 100.0),
 ('Niger', 'zinder, niger', 'near zinder', 83.33333333333334),
 ('Niger', 'dosso', 'near dosso', 66.66666666666667),
 ('Niger',
  'tahoua, dosso, tillaberi',
  'maradi, tahoua, tillaberi, dosso',
  85.71428571428572),
 ('Niger', 'dosso', 'near dosso', 66.66666666666667),
 ('Rwanda',
  'western, southern, eastern',
  'northern, western and southern provinces',
  66.66666666666667),
 ('Burundi',
  'western burundi (bubanza, bujumbura, cibitoke, makamba, and rumonge)',
  'bujumbura mairie, bujumbura rural, rumonge, makamba and cibitoke.',
  67.66917293233084),
 ('Peru',
  'ayacucho, huancavelica, junin',
  'cusco, huancavelica provinces',
  72.41379310344827),
 ('Nigeria', 'kaduna and kano states', 'kaduna state', 70.58823529411764),
 ('The Comoros', "ile d'anjouan", 'anjouan province', 68.96551724137932),
 ('The Comoros', "ile d'anjouan", 'anjouan province', 68.96551724137932),
 ('South Africa',
  'free state and kwazulu natal',
  'kwazulu-natal, eastern cape, free state provinces',
  67.53246753246754)]

In [31]:
for country, rhomis_region, matched_loc, score in matches:
    print(f"\n=== Match in {country} ({score:.1f}) ===")
    print("RHoMIS region:", rhomis_region)

    # find rows in rhomis_meta
    rhomis_rows = rhomis_meta[
        (rhomis_meta['Country full name'] == country) &
        (rhomis_meta['Regions'] == rhomis_region)
    ]
    print("RHoMIS rows:")
    print(rhomis_rows)

    # find rows in disasters
    disaster_rows = disasters[disasters['Location'] == matched_loc]
    print("Disaster rows:")
    print(disaster_rows)

=== Match in Mali (72.0) ===
RHoMIS region: segou, mopti,
RHoMIS rows:
       RHoMIS ID Country full name        Regions  Year
101  ML_PRA_2021              Mali  segou, mopti,  2021
Disaster rows:
             DisNo. Country      Location  Start Year
1645  2022-0654-MLI    Mali  mopti region        2022

=== Match in Mali (100.0) ===
RHoMIS region:
RHoMIS rows:
       RHoMIS ID Country full name Regions  Year
111  ML_MC3_2022              Mali          2022
Disaster rows:
             DisNo.      Country Location  Start Year
23    2013-0102-NPL        Nepal                 2013
46    2013-0181-MAR      Morocco                 2013
80    2013-0353-KEN        Kenya                 2013
131   2013-0480-NGA      Nigeria                 2013
139   2013-0493-NIC    Nicaragua                 2013
...             ...          ...      ...         ...
2061  2024-0892-KEN        Kenya                 2024
2063  2024-0902-MWI       Malawi                 2024
2064  2024-0910-COM  The Comoros                 2024
2074  2024-0969-TZA     Tanzania                 2024
2078  2024-9197-MWI       Malawi                 2024

[101 rows x 4 columns]

=== Match in Guatemala (100.0) ===
RHoMIS region:
RHoMIS rows:
       RHoMIS ID Country full name Regions  Year
107  GT_CAT_2022         Guatemala          2022
Disaster rows:
             DisNo.      Country Location  Start Year
23    2013-0102-NPL        Nepal                 2013
46    2013-0181-MAR      Morocco                 2013
80    2013-0353-KEN        Kenya                 2013
131   2013-0480-NGA      Nigeria                 2013
139   2013-0493-NIC    Nicaragua                 2013
...             ...          ...      ...         ...
2061  2024-0892-KEN        Kenya                 2024
2063  2024-0902-MWI       Malawi                 2024
2064  2024-0910-COM  The Comoros                 2024
2074  2024-0969-TZA     Tanzania                 2024
2078  2024-9197-MWI       Malawi                 2024

[101 rows x 4 columns]

=== Match in Tanzania (100.0) ===
RHoMIS region:
RHoMIS rows:
      RHoMIS ID Country full name Regions  Year
97  TZ_CRP_2021          Tanzania          2021
Disaster rows:
             DisNo.      Country Location  Start Year
23    2013-0102-NPL        Nepal                 2013
46    2013-0181-MAR      Morocco                 2013
80    2013-0353-KEN        Kenya                 2013
131   2013-0480-NGA      Nigeria                 2013
139   2013-0493-NIC    Nicaragua                 2013
...             ...          ...      ...         ...
2061  2024-0892-KEN        Kenya                 2024
2063  2024-0902-MWI       Malawi                 2024
2064  2024-0910-COM  The Comoros                 2024
2074  2024-0969-TZA     Tanzania                 2024
2078  2024-9197-MWI       Malawi                 2024

[101 rows x 4 columns]

=== Match in Ethiopia (66.7) ===
RHoMIS region: amhara
RHoMIS rows:
       RHoMIS ID Country full name Regions  Year
34   ET_TA6_2018          Ethiopia  amhara  2018
94   ET_PCS_2020          Ethiopia  amhara  2020
117  ET_LCS_2022          Ethiopia  amhara  2022
Disaster rows:
            DisNo.   Country      Location  Start Year
943  2018-0402-ETH  Ethiopia  amhara state        2018

=== Match in Ethiopia (66.7) ===
RHoMIS region: amhara
RHoMIS rows:
       RHoMIS ID Country full name Regions  Year
34   ET_TA6_2018          Ethiopia  amhara  2018
94   ET_PCS_2020          Ethiopia  amhara  2020
117  ET_LCS_2022          Ethiopia  amhara  2022
Disaster rows:
            DisNo.   Country      Location  Start Year
943  2018-0402-ETH  Ethiopia  amhara state        2018

=== Match in Ethiopia (66.7) ===
RHoMIS region: amhara
RHoMIS rows:
       RHoMIS ID Country full name Regions  Year
34   ET_TA6_2018          Ethiopia  amhara  2018
94   ET_PCS_2020          Ethiopia  amhara  2020
117  ET_LCS_2022          Ethiopia  amhara  2022
Disaster rows:
            DisNo.   Country      Location  Start Year
943  2018-0402-ETH  Ethiopia  amhara state        2018

=== Match in Vietnam (100.0) ===
RHoMIS region: dak lak
RHoMIS rows:
       RHoMIS ID Country full name  Regions  Year
115  VN_VSC_2022           Vietnam  dak lak  2022
Disaster rows:
             DisNo.  Country Location  Start Year
1618  2022-0515-VNM  Vietnam  dak lak        2022

=== Match in DRC (100.0) ===
RHoMIS region: bukavu
RHoMIS rows:
      RHoMIS ID Country full name Regions  Year
17  CD_CLP_2017               DRC  bukavu  2017
Disaster rows:
             DisNo. Country Location  Start Year
1068  2019-0342-COD     DRC   bukavu        2019
1260  2020-0236-COD     DRC   bukavu        2020
1861  2023-0827-COD     DRC   bukavu        2023

=== Match in Niger (83.3) ===
RHoMIS region: zinder, niger
RHoMIS rows:
      RHoMIS ID Country full name        Regions  Year
31  NE_GLD_2018             Niger  zinder, niger  2018
Disaster rows:
            DisNo. Country     Location  Start Year
109  2013-0423-NER   Niger  near zinder        2013

=== Match in Niger (66.7) ===
RHoMIS region: dosso
RHoMIS rows:
       RHoMIS ID Country full name Regions  Year
69   NE_T11_2019             Niger   dosso  2019
112  NE_NA6_2022             Niger   dosso  2022
Disaster rows:
            DisNo. Country    Location  Start Year
761  2017-0420-NER   Niger  near dosso        2017

=== Match in Niger (85.7) ===
RHoMIS region: tahoua, dosso, tillaberi
RHoMIS rows:
       RHoMIS ID Country full name                   Regions  Year
102  NE_PRA_2021             Niger  tahoua, dosso, tillaberi  2021
Disaster rows:
             DisNo. Country                          Location  Start Year
1276  2020-0336-NER   Niger  maradi, tahoua, tillaberi, dosso        2020

=== Match in Niger (66.7) ===
RHoMIS region: dosso
RHoMIS rows:
       RHoMIS ID Country full name Regions  Year
69   NE_T11_2019             Niger   dosso  2019
112  NE_NA6_2022             Niger   dosso  2022
Disaster rows:
            DisNo. Country    Location  Start Year
761  2017-0420-NER   Niger  near dosso        2017

=== Match in Rwanda (66.7) ===
RHoMIS region: western, southern, eastern
RHoMIS rows:
      RHoMIS ID Country full name                     Regions  Year
47  RW_OAF_2018            Rwanda  western, southern, eastern  2018
Disaster rows:
             DisNo. Country                                  Location  \
1758  2023-0267-RWA  Rwanda  northern, western and southern provinces

      Start Year
1758        2023

=== Match in Burundi (67.7) ===
RHoMIS region: western burundi (bubanza, bujumbura, cibitoke, makamba, and rumonge)
RHoMIS rows:
       RHoMIS ID Country full name  \
113  BI_PRD_2022           Burundi

                                               Regions  Year
113  western burundi (bubanza, bujumbura, cibitoke,...  2022
Disaster rows:
             DisNo.  Country  \
1914  2024-0232-BDI  Burundi

                                               Location  Start Year
1914  bujumbura mairie, bujumbura rural, rumonge, ma...        2024

=== Match in Peru (72.4) ===
RHoMIS region: ayacucho, huancavelica, junin
RHoMIS rows:
      RHoMIS ID Country full name                        Regions  Year
53  PE_MKP_2018              Peru  ayacucho, huancavelica, junin  2018
Disaster rows:
            DisNo. Country                       Location  Start Year
307  2014-0534-PER    Peru  cusco, huancavelica provinces        2014

=== Match in Nigeria (70.6) ===
RHoMIS region: kaduna and kano states
RHoMIS rows:
      RHoMIS ID Country full name                 Regions  Year
57  NG_GLT_2019           Nigeria  kaduna and kano states  2019
Disaster rows:
             DisNo.  Country      Location  Start Year
1609  2022-0464-NGA  Nigeria  kaduna state        2022

=== Match in The Comoros (69.0) ===
RHoMIS region: ile d'anjouan
RHoMIS rows:
       RHoMIS ID Country full name        Regions  Year
77   KM_DHA_2019       The Comoros  ile d'anjouan  2019
105  KM_DHA_2021       The Comoros  ile d'anjouan  2021
Disaster rows:
            DisNo.      Country          Location  Start Year
226  2014-0258-COM  The Comoros  anjouan province        2014

=== Match in The Comoros (69.0) ===
RHoMIS region: ile d'anjouan
RHoMIS rows:
       RHoMIS ID Country full name        Regions  Year
77   KM_DHA_2019       The Comoros  ile d'anjouan  2019
105  KM_DHA_2021       The Comoros  ile d'anjouan  2021
Disaster rows:
            DisNo.      Country          Location  Start Year
226  2014-0258-COM  The Comoros  anjouan province        2014

=== Match in South Africa (67.5) ===
RHoMIS region: free state and kwazulu natal
RHoMIS rows:
      RHoMIS ID Country full name                       Regions  Year
89  ZA_NEO_2020      South Africa  free state and kwazulu natal  2020
Disaster rows:
             DisNo.       Country  \
1025  2019-0176-ZAF  South Africa

                                               Location  Start Year
1025  kwazulu-natal, eastern cape, free state provinces        2019